import { v4 as uuid } from 'uuid';
import { DocumentModel } from '@/types/document';

export function createSeedDocument(): DocumentModel {
  const now = new Date().toISOString();
  return {
    id: uuid(),
    title: 'MVP Study Sheet',
    createdAt: now,
    updatedAt: now,
    pages: [
      {
        id: uuid(),
        size: 'letter-portrait',
        backgroundColor: '#ffffff',
        blocks: [
          {
            id: uuid(),
            type: 'heading',
            content: 'Physics Cheat Sheet',
            x: 40,
            y: 30,
            width: 736,
            height: 50,
            naturalWidth: 736,
            naturalHeight: 50,
            naturalFontSize: 28,
            zIndex: 1,
            styles: {
              fontSize: 28,
              fontWeight: 'bold',
              textColor: '#1a1a1a',
              alignment: 'center',
              padding: 8,
            },
          },
          {
            id: uuid(),
            type: 'divider',
            x: 40,
            y: 90,
            width: 736,
            height: 4,
            zIndex: 2,
            thickness: 2,
            color: '#374151',
            styles: {},
          },
          {
            id: uuid(),
            type: 'bullet-list',
            items: [
              "Newton's First Law: An object at rest stays at rest",
              'Newton\'s Second Law: F = ma',
              "Newton's Third Law: Every action has an equal and opposite reaction",
            ],
            bulletStyle: 'dot',
            x: 40,
            y: 110,
            width: 350,
            height: 140,
            naturalWidth: 350,
            naturalHeight: 140,
            naturalFontSize: 13,
            zIndex: 3,
            styles: {
              fontSize: 13,
              textColor: '#1f2937',
              padding: 12,
            },
          },
          {
            id: uuid(),
            type: 'formula',
            content: 'F = ma\nE = mc²\nv = v₀ + at\ns = v₀t + ½at²',
            x: 420,
            y: 110,
            width: 356,
            height: 140,
            naturalWidth: 356,
            naturalHeight: 140,
            naturalFontSize: 16,
            zIndex: 4,
            styles: {
              fontSize: 16,
              textColor: '#1e40af',
              backgroundColor: '#eff6ff',
              padding: 16,
              borderColor: '#bfdbfe',
              borderWidth: 1,
            },
          },
          {
            id: uuid(),
            type: 'box',
            x: 40,
            y: 270,
            width: 736,
            height: 100,
            zIndex: 5,
            styles: {
              backgroundColor: '#fef3c7',
              borderColor: '#f59e0b',
              borderWidth: 2,
              padding: 16,
            },
          },
          {
            id: uuid(),
            type: 'text',
            content: '⚡ Key Tip: Always check your units! Dimensional analysis catches most calculation errors before they happen.',
            x: 56,
            y: 286,
            width: 704,
            height: 68,
            naturalWidth: 704,
            naturalHeight: 68,
            naturalFontSize: 14,
            zIndex: 6,
            styles: {
              fontSize: 14,
              fontWeight: 'bold',
              textColor: '#92400e',
              alignment: 'left',
              padding: 8,
            },
          },
        ],
      },
    ],
  };
}
